export const fakeData = [
    {
        "id": 1,
        "first_name": "Heindrick",
        "last_name": "Caselli",
        "email": "hcaselli0@umich.edu",
        "gender": "Polygender",
        "ip_address": "68.60.167.138"
    }, {
        "id": 2,
        "first_name": "Marline",
        "last_name": "Harsnep",
        "email": "mharsnep1@aboutads.info",
        "gender": "Female",
        "ip_address": "101.7.45.72"
    }, {
        "id": 3,
        "first_name": "Emelyne",
        "last_name": "Brant",
        "email": "ebrant2@army.mil",
        "gender": "Genderqueer",
        "ip_address": "212.28.187.235"
    }, {
        "id": 4,
        "first_name": "Sebastien",
        "last_name": "Dutnall",
        "email": "sdutnall3@etsy.com",
        "gender": "Agender",
        "ip_address": "254.29.147.143"
    }, {
        "id": 5,
        "first_name": "Brittney",
        "last_name": "Askell",
        "email": "baskell4@histats.com",
        "gender": "Female",
        "ip_address": "181.94.97.23"
    }, {
        "id": 6,
        "first_name": "Eba",
        "last_name": "Bairstow",
        "email": "ebairstow5@who.int",
        "gender": "Male",
        "ip_address": "3.2.94.193"
    }, {
        "id": 7,
        "first_name": "Averil",
        "last_name": "Guerreru",
        "email": "aguerreru6@ask.com",
        "gender": "Bigender",
        "ip_address": "245.249.112.74"
    }, {
        "id": 8,
        "first_name": "Malia",
        "last_name": "Rosberg",
        "email": "mrosberg7@deliciousdays.com",
        "gender": "Female",
        "ip_address": "83.82.42.157"
    }, {
        "id": 9,
        "first_name": "Joete",
        "last_name": "Scryne",
        "email": "jscryne8@stumbleupon.com",
        "gender": "Agender",
        "ip_address": "123.17.211.250"
    }, {
        "id": 10,
        "first_name": "Jessi",
        "last_name": "MacDonough",
        "email": "jmacdonough9@cpanel.net",
        "gender": "Agender",
        "ip_address": "71.224.251.32"
    }
]